from enum import Enum

class ScanStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class AssetType(str, Enum):
    ALGORITHM = "ALGORITHM"
    API_CALL = "API_CALL"
    CERTIFICATE = "CERTIFICATE"
    CONTAINER = "CONTAINER"
    DEPENDENCY = "DEPENDENCY"
    PROTOCOL = "PROTOCOL"
    BINARY = "BINARY"
    VENDOR_MANAGED = "VENDOR_MANAGED"

class CryptoPurpose(str, Enum):
    SIGNATURE = "SIGNATURE"
    DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE"
    KEY_ESTABLISHMENT = "KEY_ESTABLISHMENT"
    ENCRYPTION = "ENCRYPTION"
    HASHING = "HASHING"
    MAC = "MAC"
    PASSWORD_DERIVATION = "PASSWORD_DERIVATION"
    AUTHENTICATION = "AUTHENTICATION"
    UNKNOWN = "UNKNOWN"

class RiskLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class EvidenceType(str, Enum):
    OBSERVED = "OBSERVED"
    INFERRED = "INFERRED"
    ASSUMED = "ASSUMED"
    EXTERNAL = "EXTERNAL"

class StandardStatus(str, Enum):
    FINAL_STANDARD = "FINAL_STANDARD"
    STANDARDIZATION_IN_PROGRESS = "STANDARDIZATION_IN_PROGRESS"
    RESEARCH_NON_STANDARD = "RESEARCH_NON_STANDARD"

class ThreatScenarioType(str, Enum):
    HARVEST_NOW_DECRYPT_LATER = "HARVEST_NOW_DECRYPT_LATER"
    QUANTUM_SIGNATURE_FORGERY = "QUANTUM_SIGNATURE_FORGERY"
    LONG_LIVED_DATA_EXPOSURE = "LONG_LIVED_DATA_EXPOSURE"
    CONSERVATIVE = "CONSERVATIVE"
    MODERATE = "MODERATE"
    AGGRESSIVE = "AGGRESSIVE"
    CUSTOM = "CUSTOM"

class ValidationStatus(str, Enum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"

class QuantumSafety(str, Enum):
    QUANTUM_VULNERABLE = "QUANTUM_VULNERABLE"
    QUANTUM_RESISTANT_WITH_REDUCED_SECURITY_MARGIN = "QUANTUM_RESISTANT_WITH_REDUCED_SECURITY_MARGIN"
    NOT_DIRECTLY_QUANTUM_VULNERABLE = "NOT_DIRECTLY_QUANTUM_VULNERABLE"
    QUANTUM_SAFE = "QUANTUM_SAFE"
    HYBRID = "HYBRID"
    UNKNOWN = "UNKNOWN"

class RecommendationCategory(str, Enum):
    PQC_REPLACEMENT = "PQC_REPLACEMENT"
    MIGRATE_PQC = "MIGRATE_PQC"
    HYBRID = "HYBRID"
    RETAIN = "RETAIN"
    RETAIN_SYMMETRIC_CRYPTO = "RETAIN_SYMMETRIC_CRYPTO"
    RETAIN_HASH = "RETAIN_HASH"
    RETAIN_MAC = "RETAIN_MAC"
    RETAIN_PASSWORD_DERIVATION = "RETAIN_PASSWORD_DERIVATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"

class ReviewStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"

class TestingRequirement(str, Enum):
    __test__ = False
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    REGULATED = "REGULATED"

class TaskType(str, Enum):
    DISCOVERY_REVIEW = "DISCOVERY_REVIEW"
    CRYPTO_API_CHANGE = "CRYPTO_API_CHANGE"
    ALGORITHM_REPLACEMENT = "ALGORITHM_REPLACEMENT"
    HYBRID_DEPLOYMENT = "HYBRID_DEPLOYMENT"
    KEY_MANAGEMENT_CHANGE = "KEY_MANAGEMENT_CHANGE"
    CERTIFICATE_UPDATE = "CERTIFICATE_UPDATE"
    PROTOCOL_UPDATE = "PROTOCOL_UPDATE"
    DEPENDENCY_UPDATE = "DEPENDENCY_UPDATE"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"
    APPLICATION_TESTING = "APPLICATION_TESTING"
    INTEROPERABILITY_TESTING = "INTEROPERABILITY_TESTING"
    PERFORMANCE_TESTING = "PERFORMANCE_TESTING"
    SECURITY_VALIDATION = "SECURITY_VALIDATION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    VENDOR_REVIEW = "VENDOR_REVIEW"

class TaskStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    READY = "READY"
    BLOCKED = "BLOCKED"
    IN_PROGRESS = "IN_PROGRESS"
    VALIDATION_REQUIRED = "VALIDATION_REQUIRED"
    COMPLETED = "COMPLETED"

class MigrationPriority(str, Enum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"

class ImpactLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class SimulationStatus(str, Enum):
    CREATED = "CREATED"
    PREPARING = "PREPARING"
    SIMULATING = "SIMULATING"
    TRANSFORMED = "TRANSFORMED"
    BUILDING = "BUILDING"
    TESTING = "TESTING"
    VALIDATING = "VALIDATING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

class ValidationCheckType(str, Enum):
    SYNTAX = "SYNTAX"
    IMPORT = "IMPORT"
    BUILD = "BUILD"
    UNIT_TEST = "UNIT_TEST"
    INTEGRATION_TEST = "INTEGRATION_TEST"
    CRYPTO_CONFIGURATION = "CRYPTO_CONFIGURATION"
    DEPENDENCY_CHECK = "DEPENDENCY_CHECK"
    COMPATIBILITY = "COMPATIBILITY"
    PERFORMANCE = "PERFORMANCE"
    SECURITY = "SECURITY"

class ValidationCheckStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"
    BLOCKED = "BLOCKED"
    NOT_RUN = "NOT_RUN"
